apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fbi-ucr

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/part-of: fbi-ucr
  app.kubernetes.io/managed-by: kustomize
